branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

os: linux

language: node_js

node_js:
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

before_script:
  - yarn build

script:
  - yarn test

jobs:
  include:
    - name: Commit lint
      stage: test
      script:
        - yarn commitlint-travis

    - name: Test
      stage: test
      script:
        - yarn test

    - stage: npm release
        if: tag IS present
        script: skip
        deploy:
          provider: npm
          skip_cleanup: true
          on:
            tags: true
            branch: master
