import path from "path";

const DECLARATIONS_DTS_FILENAME = "declaration.d.ts";
const DECLARATIONS_DTS_ROOT_PATH = path.join(
  "types/common/",
  DECLARATIONS_DTS_FILENAME
);
const EVENT_HANDLERS_JSON_FILENAME = "eventHandlers.json";
const $w_MODULE_NAME = "$w";

const $W_GLOBAL_COMMENTS = {
  DECLARATION_COMMENT: "$W_GLOBAL_DECLARATION_COMMENT",
  NAMESPACE_COMMENT: "$W_NAMESPACE_COMMENT",
  $W_TYPE_DECLARATION_COMMENT: "$W_TYPE_DECLARATION_COMMENT"
};
const $W_MEMBERS_KEY = "/** ##$W_NAMESPACE_MEMBERS## */";
const QUERYABLE_TYPE = "TypeNameToSdkType";
export default {
  DECLARATIONS_DTS_FILENAME,
  DECLARATIONS_DTS_ROOT_PATH,
  EVENT_HANDLERS_JSON_FILENAME,
  $w_MODULE_NAME,
  $W_GLOBAL_COMMENTS,
  $W_MEMBERS_KEY,
  QUERYABLE_TYPE
};
