import path from "path";
const DIST_BUILD_FOLDER = "dist";
const SRC_TYPES_FOLDER = "src_types";
const DEST_TYPES_FOLDER = "types";
const DEST_COMMON_FOLDER = "common";
const DEST_PAGES_FOLDER = "pages";

const EVENT_HANDLERS_JSON_FILENAME = "eventHandlers.json";
const DECLARATIONS_DTS_FILENAME = "declaration.d.ts";
const DECLARATIONS_DTS_FILENAME_DEPRECATED = "declaration.deprecated.d.ts";
const $W_DECLARATION_FULL_FILENAME = "$w.d.ts";
const MODULE_LIST_FILENAME = "wixModules.json";
const FULL_CORVID_DECLARATION_FILENAME = "fullCorvidTypes.json";
const FULL_CORVID_DECLARATION_FILENAME_DEPRECATED =
  "fullCorvidTypes.deprecated.json";
const TYPES_COMMON_PATH = path.join(DEST_TYPES_FOLDER, DEST_COMMON_FOLDER);
const TYPES_PAGES_PATH = path.join(DEST_TYPES_FOLDER, DEST_PAGES_FOLDER);
const DECLARATIONS_DTS_ROOT_PATH = path.join(
  DEST_TYPES_FOLDER,
  DECLARATIONS_DTS_FILENAME
);
const DECLARATIONS_DTS_ROOT_PATH_DEPRECATED = path.join(
  DEST_TYPES_FOLDER,
  DECLARATIONS_DTS_FILENAME_DEPRECATED
);

const $W_MODULE_NAME = "$w";
const $W_GLOBAL_COMMENTS = {
  DECLARATION_COMMENT: "$W_GLOBAL_DECLARATION_COMMENT",
  NAMESPACE_COMMENT: "$W_NAMESPACE_COMMENT",
  $W_TYPE_DECLARATION_COMMENT: "$W_TYPE_DECLARATION_COMMENT"
};
const $W_MEMBERS_KEY = "/** ##$W_NAMESPACE_MEMBERS## */";
const QUERYABLE_TYPE = "TypeNameToSdkType";

export default {
  $W_MODULE_NAME,
  $W_GLOBAL_COMMENTS,
  $W_MEMBERS_KEY,
  QUERYABLE_TYPE,
  DIST_BUILD_FOLDER,
  DEST_PAGES_FOLDER,
  DEST_COMMON_FOLDER,
  DEST_TYPES_FOLDER,
  SRC_TYPES_FOLDER,
  TYPES_COMMON_PATH,
  TYPES_PAGES_PATH,
  DECLARATIONS_DTS_ROOT_PATH,
  MODULE_LIST_FILENAME,
  DECLARATIONS_DTS_FILENAME,
  EVENT_HANDLERS_JSON_FILENAME,
  $W_DECLARATION_FULL_FILENAME,
  FULL_CORVID_DECLARATION_FILENAME,
  FULL_CORVID_DECLARATION_FILENAME_DEPRECATED,
  DECLARATIONS_DTS_FILENAME_DEPRECATED,
  DECLARATIONS_DTS_ROOT_PATH_DEPRECATED
};
