// the first part of this file is being generated by => scripts/selector-declaration-builder.js
// Run `npm run generate-dts` to generate it
//todo:: try to improve intersectionArray
type IntersectionArrayAndBase<T, P> = {
    [K in keyof T]: K extends P ? T[K] : T[K] & T[K][];
};
type CommaChar = ","
type LegalChars = CommaChar | " " | "\n" | "\t"
type WixElements = PageElementsMap & IntersectionArrayAndBase<TypeNameToSdkType, 'Document'>;
type NicknameSelector = keyof PageElementsMap
type TypeSelector = keyof IntersectionArrayAndBase<TypeNameToSdkType, 'Document'>

type WixElementSelector = NicknameSelector | TypeSelector
type VaildSelectorsChars = WixElementSelector | LegalChars

type OnlyVaildSelectorsChars<S> =
    S extends ""
        ? any
        : S extends `${VaildSelectorsChars}${infer Tail}`
            ? OnlyVaildSelectorsChars<Tail>
            : never

type HasComma<S> = 
    S extends `${CommaChar}${infer Tail}`
        ? unknown
        : S extends `${VaildSelectorsChars}${infer Tail2}`
            ? HasComma<Tail2>
            : never
type MultiSelector<S> = S & OnlyVaildSelectorsChars<S> & HasComma<S>
/**
 * Selects and returns elements from a page.
 */
declare function $w<T extends WixElementSelector, S extends string>(selector: T | MultiSelector<S>):
    S extends keyof WixElements 
        ? WixElements[S]
        : any
/**
 * The `$w` namespace contains everything you need in order to work
 *  with your site's components.
 */
declare namespace $w {
    /**
     * Gets a selector function for a specific context.
     */
    function at(context: $w.Event.EventContext): $w.$w;

    /**
     * Sets the function that runs when all the page elements have finished loading.
     */
    function onReady(initFunction: $w.ReadyHandler): void;

    /**
     * Selects and returns elements from a page.
     */
    type $w = <T extends WixElementSelector, S extends string>(selector: T | MultiSelector<S>) =>
        S extends keyof WixElements 
            ? WixElements[S]
            : any
}

