// the first part of this file is being generated by => scripts/selector-declaration-builder.js
// Run `npm run generate-dts` to generate it

type IntersectionArrayAndBase<T, P> = {
    [K in keyof T]: K extends P ? T[K] : T[K] & T[K][];
};
type CommaChar = ","
type LegalChars = CommaChar | " " | "\n" | "\t"
type WixElements = PageElementsMap & IntersectionArrayAndBase<TypeNameToSdkType, 'Document'>;
type NicknameSelector = keyof PageElementsMap
type TypeSelector = keyof IntersectionArrayAndBase<TypeNameToSdkType, 'Document'>

type WixElementSelector = NicknameSelector | TypeSelector
type VaildSelectorsChars = WixElementSelector | LegalChars

type OnlyVaildSelectorsChars<S> =
    S extends ""
        ? unknown
        : S extends `${VaildSelectorsChars}${infer Tail}`
            ? OnlyVaildSelectorsChars<Tail>
            : never

type HasComma<S> = 
    S extends `${CommaChar}${infer Tail}`
        ? unknown
        : S extends `${VaildSelectorsChars}${infer Tail}`
            ? HasComma<Tail>
            : never
            
type MultiSelector<S> = S & OnlyVaildSelectorsChars<S> & HasComma<S>
/**
 * $W_GLOBAL_DECLARATION_COMMENT
 */
declare function $w<T extends WixElementSelector, S extends string>(selector: T | MultiSelector<S>):
    S extends keyof WixElements 
        ? WixElements[S]
        : any
/**
 * $W_NAMESPACE_COMMENT
 */
declare namespace $w {
    /** $W_NAMESPACE_MEMBERS */
    /**
     * $W_$W_DECLARATION_COMMENT
     */
    type $w = <T extends WixElementSelector, S extends string>(selector: T | MultiSelector<S>) =>
        S extends keyof WixElements 
            ? WixElements[S]
            : any
}

