// the first part of this file is being generated by => scripts/selector-declaration-builder.js
// Run `npm run generate-dts` to generate it
declare type IntersectionArrayAndBase<T, P> = {
    [K in keyof T]: K extends P ? T[K] : T[K] & T[K][];
};


declare type TypeSelectorMap = IntersectionArrayAndBase<TypeNameToSdkType, 'Document'>;
declare type WixElements = PageElementsMap & TypeSelectorMap
declare type NicknameSelector = keyof PageElementsMap
declare type TypeSelector = keyof TypeSelectorMap

declare type WixElementSelector = NicknameSelector | TypeSelector
declare type IsWixElementSelector<S> = S extends WixElementSelector ? WixElements[S] : never;
/**
 * $W_GLOBAL_DECLARATION_COMMENT
 */
declare function $w<T extends WixElementSelector, S extends string>(selector: T | S & IsWixElementSelector<S>):
    S extends keyof WixElements 
        ? WixElements[S]
        : any
/**
 * $W_NAMESPACE_COMMENT
 */
declare namespace $w {
    /** ##$W_NAMESPACE_MEMBERS## */
    /**
     * $W_TYPE_DECLARATION_COMMENT
     */
    type $w = <T extends WixElementSelector, S extends string>(selector: T | S & IsWixElementSelector<S>) =>
        S extends keyof WixElements 
            ? WixElements[S]
            : any
}

