name: Publish
on:
  push:
    tags: 
      - '**'
  repository_dispatch:
    types: [docs_updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Publish 
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
